### ISSUE TITLE
Controls drop out

### ISSUE THREAD

**Issue by thetonestarr** [Moehammered/switch-remote-play#2]
Frequently, while playing, the controls become completely unresponsive. This happens both with joycons connected or wireless, but controllers wired into the PC work during this time. 

The joycons become responsive again usually within twenty seconds or so. 

Can confirm it's not an issue with the joycons themselves. Don't believe it's a problem with my system itself but have not ruled that out, but I don't ever have problems with remote play with Oculus Quest 2, which leads me to believe it's the software.

**Comment by Moehammered** [comment]
Hey there, sorry to hear the controls are dropping out for you.

My hunch is led to believe it is a network issue or the host application. To better help diagnose this can you tell me:
- your PC configuration (CPU, RAM, GPU, Network connection type)
- if you're using the switch via ethernet or wifi?

As for a suggested thing to try:
- Can you try using your switch docked connected via ethernet if possible?
- Does it happen when the encoder settings are catered for performance?
  - Preset = ultra fast
  - quality control factor = 30
  - bitrate = 5120kb~

Looking at the Oculus Quest I'm assuming your system is quite powerful. So it lends me to believe there's a network issue. I'm assuming the Oculus Quest has you connect your controllers via bluetooth to the PC?

*Below is my personal experience so far on my machine for reference purposes.*

Personal experience for me I've never had the controls dropout, I even play approximately 3 meters away from my PC, playing Tekken 7 online, and no issues. 

My PC configuration is:
- Network: Wifi 5Ghz
- CPU: Ryzen 5 2600 stock
- RAM: 16GB 3200 Mhz
- GPU: 5600 XT no overclock
- SSD: 1TB

My Switch configuration is:
- Network: Wifi 5Ghz
- CPU: very low overclock
- RAM: very low overclock
- CFW: Atmosphere 0.16.1
- System FW: 10.2
- CFW on NAND (not emunand)

Now the odd thing is, either there is a performance issue with the host (PC) receiving the input data or the network. The protocol used to transfer inputs is TCP/IP so that will explain how the controls eventually return. If it were a complete dropout then the controls will die as the program is designed to terminate if the connection from the switch sending controls disconnects or drops out.

**Comment by thetonestarr** [comment]
Thanks for the quick response, Moehammered!

My PC is wired via Cat6 through a gigabit switch, but I have been using the Switch wireless in handheld. I will see if using it in a wired config works better, but I have my doubts, as the only USB Ethernet adapter I have is a Wii adapter, which has a lower max transfer rate than my 802.11AC-capable wifi. Nonetheless, I will give it a try!

My PC is as follows:
-Ryzen 3700x
-GTX 1660Ti
-32GB PC4-25600 (3200MHz, but I just found out that according to WMIC, it's only running at 2133... gonna have to fix that)
-1TB M.2 NVMe SSD

Switch is not overclocked, running Atmosphere 0.17.1, sys FW is 11.0.1. Wifi is Google Wifi (NOT Nest Wifi), running in mesh configuration. It automatically chooses 2.4GHz or 5GHz - I can't manually select this, regrettably (one of the reasons I'm considering switching).

Oculus Quest does indeed *normally* connect by USB, but - just like with Switch - there are third party workarounds. I am using an 'unapproved' (not authorized by Oculus but officially released on his website by the original developer) copy of Remote Desktop, which effectively does the exact same thing Switch Remote Play does.

My desktop is in the basement of my house, whilst I have been able to flawlessly (latency in the ballpark of 10-15ms) play Beat Saber or Half-Life Alyx remotely from my bedroom on the 2nd floor on the other side of the house (2 floors and roughly a total of 30 feet of air between Oculus and PC, but only ~10ft from the primary wifi node & the next, then ~15 from that node to the one that services my bedroom). 

I haven't yet looked into changing the encoder settings but that will be the first thing I try. Will report back after that and (if necessary) playing the Switch docked & wired.

**Comment by Moehammered** [comment]
Hey there, any updates on this?

I wanted to also suggest trying out moonlight-nx or SkyNX to see if you get the same control issues with those.
Moonlight-nx is fairly different as is it uses the NVidia game streaming software. SkyNX is similar to this as both use ffmpeg to stream video to the switch and handle controls independently.

If SkyNX ends up having no control issues, then might I ask you uninstall the ViGEm Bus Driver v1.16 and instead try installing the latest ViGEm Bus Driver. Then attempt using switch-remote-play again to see if the control issue resolves.

Hope that helps.

**Comment by Moehammered** [comment]
@thetonestarr hey there I just made a release with some fixes to controller input for certain network environments. Could you test the latest release and let me know if the control issues are resolved?

If I don't receive a reply by the end of the week I will close the issue as by then it will be stale.

**Comment by Moehammered** [comment]
closing issue as there's no response. See issue https://github.com/Moehammered/switch-remote-play/issues/13 for similar issue being tracked.
