### ISSUE TITLE
The stream on the switch screen freezes when a fullscreen application is launched on the computer 

### ISSUE THREAD

**Issue by SajmonOriginal** [Moehammered/switch-remote-play#25]

**Comment by Moehammered** [comment]
Hi there. Could you please tell me what application you're launching? Is it exclusive fullscreen or borderless fullscreen?

**Comment by drnooooo** [comment]
I have the same problem with Citra emulator. Trying to run OOT3D in full screen or using any kind of borderless window app will always cause SRP to stop working. This happens regardless of what app I use to stream, not just SRP, as well as recording software like AMD ReLive, so it's possible that Citra just doesn't like being recorded in fullscreen, but I'm not sure.

**Comment by Moehammered** [comment]
Thank you very much for giving me an example to test this issue with :)

When I have time I will investigate this while testing citra. I'm curious now, does OBS have the same issue?

**Comment by drnooooo** [comment]
OBS is the only thing that doesn't have this issue for me and I've been able to get it to record using that, yeah. I don't know what the difference is though, it doesn't seem related to any settings in Citra.

**Comment by rods012** [comment]
This is also occurring to me when I launch Retroarch. I am not trying to stream or anything, just by starting the application in fullscreen the image freezes. If I switch to anything else it works as intended. This includes Windowed fullscreen, so if I have a window open in front of Retroarch SRP shows Retroarch working normally.

**Comment by Moehammered** [comment]
> This is also occurring to me when I launch Retroarch. I am not trying to stream or anything, just by starting the application in fullscreen the image freezes. If I switch to anything else it works as intended. This includes Windowed fullscreen, so if I have a window open in front of Retroarch SRP shows Retroarch working normally.

Thanks for the extra info about this.

The symptom you're experiencing is solved by using borderless fullscreen in retroarch. The reason why "normal" fullscreen "freezes" is because the application (retroarch in this example) tells windows to stop rendering the desktop and give it full display rights.

Switch Remote Play uses ffmpeg and is configured to capture the desktop via gdigrab. So once an application launches that requests fullscreen rights gdigrab and ffmpeg won't see anything because effectively the application isn't rendering on the desktop.

Hope that helps clarify why it's happening. :)

**Comment by starfire213** [comment]
How can i fix this for the gamepad view for cemu, i try to full screen it but it freezes, and i really dont want black bars

**Comment by starfire213** [comment]
@Moehammered sorry to ping you but i am not sure if you will see this

**Comment by Moehammered** [comment]
@starfire213 please see the comment I made prior to yours. Short of it is: do not use exclusive fullscreen mode. Prefer borderless fullscreen. If there isn't a birderless fullscreen option available, use the borderless gaming application to have a borderless fullscreen effect. Otherwise just use Windowed mode.

As for black bars, that would have to do with your aspect ratio and the aspect ratio of cemu. Try looking through the graphics settings of cemu for that.

Hope that clears things up a bit for you. :)
