### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by stefluid7** [Moehammered/switch-remote-play#3]
I am unable to connect my pc to the switch through remote play. My firewall is disabled and my ports are fine but I get this error everytime:
Output #0, h264, to 'tcp://192.168.0.56:20003':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1280x720, q=-1--1, 5632 kb/s, 30 fps, 30 tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 5632000/0/5632000 buffer size: 5632000 vbv_delay: N/A
Failed to connect bus for virtual controller with error code: 0xe0000001

I have tried lowering the setting but it had not worked. What should I do?

**Comment by Moehammered** [comment]
Hey there. That error code is caused by the virtual controller failing to start.

Did you follow the instructions and install the necessary software?

Can you please make sure you've installed ViGEm Bus Driver and the screen recorder software listed in the instructions? If you've already installed them can you try reinstalling them and attempting to connect?

Thanks.

**Comment by Moehammered** [comment]
https://github.com/Moehammered/switch-remote-play/issues/4

please see above for solution.
