### ISSUE TITLE
Cannot use app

### ISSUE THREAD

**Issue by RealEmanGaming** [Moehammered/switch-remote-play#33]
I configure everything according to your wiki, but as soon as I press “R” on my switch to start streaming, it causes my main monitor on my computer to go black, and then my entire computer locks up, causing me to have to hard reboot it.

**Comment by Moehammered** [comment]
Could you please provide the following:

- Switch firmware and custom firmware version
- PC details
  - windows version
  - cpu
  - gpu
  - ram
  - network interface(wifi or ethernet)

What version of the program are you using? Does this happen with older versions?

Could you provide a screenshot or image of the console output when attempting to connect?

Thanks.

**Comment by RealEmanGaming** [comment]
> Could you please provide the following:
> 
> * Switch firmware and custom firmware version
> * PC details
>   
>   * windows version
>   * cpu
>   * gpu
>   * ram
>   * network interface(wifi or ethernet)
> 
> What version of the program are you using? Does this happen with older versions?
> 
> Could you provide a screenshot or image of the console output when attempting to connect?
> 
> Thanks.

Sure thing!

* Switch:
  * Firmware: 11.0.1
  * CFW: Atmosphere 19.5 (latest version as of writing this)
* PC Specs:
  * OS: Windows 11 build 22000.100 (the exact same thing was happening before I upgraded from Windows 10 21H1)
  * CPU: Ryzen 5 2600X
  * GPU: NVIDIA GTX 1660
  * Ram: 16GB DDR4 2933MHz (if it matters)
  * Network Interface: Built-in Mobo Ethernet (Realtek 8111H Gigabit LAN controller)

I'm using the latest version of Switch Remote Play, v0.9.0, it did happen with older versions when I tried them.

I'll edit my comment with an image of the output in a little bit

**Comment by Moehammered** [comment]
Thanks for the details!

So I take it that the monitor went black and locked up in the 2nd picture?

The monitor going black is due to the resolution mode being changed by the program.
- What is your desktop resolution set to?
- What is the aspect ratio of your monitor?
- In the Switch app, is the desktop resolution setting set to 720p(1280 x 720) or 1080p(1920 x 1080)?
  - Does it occur with either setting?

Your PC being locked up is a bit odd though. I'll need to make a debug build with extra logging statements in there to help pinpoint when the lockup is occurring.

Things to try till I have time to make a debug build with extra diagnostics:
- Make sure that `ffmpeg` and `switch-remote-play-host.exe` aren't being blocked by the firewall
  -  If you are using a 3rd party antivirus, could you also check to see if it is blocking the network traffic?
- Make sure to run `switch-remote-play-host.exe` by double-clicking it
  - Don't run it by opening a cmd/powershell prompt and executing it

To make sure ffmpeg runs fine on your machine:
1. Please go to the directory where ffmpeg.exe is located
2. hold `shift` and `right-click` in the folder to see the option to *Open Powershell here*
3. Run the following command: `./ffmpeg.exe -f gdigrab -framerate 60 -i desktop gditest.mkv`
4. After abour 10 seconds or so stop the program by pressing `ctrl+c`
5. There should be a video file called gditest.mkv. If it plays fine then ffmpeg is OK.

Sorry about the trouble, and thanks for being patient :)

**Comment by Moehammered** [comment]
closed due to going stale and no response.
