### ISSUE TITLE
NVENC Support

### ISSUE THREAD

**Issue by Shinmegumi** [Moehammered/switch-remote-play#34]
I know in your documentation that you said that this was very low priority. I was looking at the encoder API library and I wanted to see what I might be able to do to help. Unless I have misread the code, I couldn't see where you made any API/encoder calls or where you were storing those functions.

I have a GTX 1070 in my current gaming PC so I would be happy to use it as a test rig and can get a few others to test on. Let me know how I can contribute and I'll happily do what I can.

**Comment by Moehammered** [comment]
Hi there. Thank you for the interest and offer of support. It is much appreciated :)

To give a bit of insight into why it is extremely low priority for me. My current GPU is an AMD 5600XT. When I am implementing the codec support, I need to do lots of testing during development. Some of that testing is trial and error to observe what codec parameters are worth displaying to the user. 

I have a GTX 1050ti. So a test machine is not much of an issue for me when implementing the support. It just requires me to uninstall my gpu then setup the 1050ti and leave it in my machine until support is complete.

The bigger concern I have is offering support once it is implemented. I get many questions and I try to answer and offer support to all of them. However, since I will not permanently have an NVIDIA gpu installed any support requests or issues with the NVIDIA codec will take a long time to resolve or I will be unable to offer support.

Considering all this, I'd rather focus on the things and issues that are universal to all users first. Especially in recent since I have little time due to full time work plus my side work.

That all said, if you know how to use ffmpeg you can definitely help me out! If you could test all h264_nvenc codec parameters in ffmpeg while recording your screen and taking note of any parameters that particularly improve latency or quality that'd be good :)

Thank you once again for the offer and your patience. :)
