### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Purcify** [Moehammered/switch-remote-play#45]
Add a bind to swap touch modes while streaming.

**Comment by Moehammered** [comment]
Thanks for the suggestion. It's a nice idea!
However, I won't be implementing this any time soon since the application is designed so that the touch mode needs to be initialised and known before the stream starts. Making it so the touch mode can change during the stream will be lots of work with lots of potential issues.

Can I ask, what modes do you want to swap between and why?

**Comment by Moehammered** [comment]
closing due to issue being stale and out of the scope of the project.
