### ISSUE TITLE
CreateProcess error code: 740 - Unable to stream on PC - Capture area (...) extends outside window area. desktop: I/O error

### ISSUE THREAD

**Issue by joaomPT** [Moehammered/switch-remote-play#51]
Hi, I downloaded this app today and Im unable to stream on my Windows 11.

I'm having the following error:

[gdigrab @ 000001fc6e5aeac0] Capture area (0,0),(576,1280) extends outside window area (0,0),(1920,1080)desktop: I/O error

I have dual monitor, tried only 1 monitor, still does not work.
Can you help me please?

Thanks in advance!

**Comment by joaomPT** [comment]
Update:
By setting ffmpeg.exe as admin, I got a different error:

ffmpeg.exe -probesize 32 -hwaccel auto -y -f gdigrab -framerate 1280 -vsync vfr -video_size 720x1280 -i desktop -f h264 -vcodec h264 -vf "scale=720x60" -preset ultrafast -crf 0 -tune zerolatency -pix_fmt yuv420p -x264-params "nal-hrd=vbr:opencl=true" -b:v 4608k -minrate 4608k -maxrate 4608k -bufsize 4608k tcp://192.168.1.157:20003
Failed to start process. CreateProcess error code: 740

**Comment by joaomPT** [comment]
Hello @Moehammered 

Thanks for the response.

Regarding your questions, I noticed that I had version mismatching. Now I'm using v1.0.0 on Nintendo Switch and PC.

And now my error is different

```
---- Virtual Controller ----
Testing for correct Virtual Controller driver installation...

    Client allocation successful.
    Virtual Controller connection failed with error code: 0xe0000001


!!! Virtual Controller driver seems to be having issues. Please make sure it is installed correctly. !!!
If the problem persists, please try uninstalling the driver and installing the latest virtual controller driver
```

**Comment by Moehammered** [comment]
> Hello @Moehammered
> 
> Thanks for the response.
> 
> Regarding your questions, I noticed that I had version mismatching. Now I'm using v1.0.0 on Nintendo Switch and PC.
> 
> And now my error is different
> 
> ```
> ---- Virtual Controller ----
> Testing for correct Virtual Controller driver installation...
> 
>     Client allocation successful.
>     Virtual Controller connection failed with error code: 0xe0000001
> 
> 
> !!! Virtual Controller driver seems to be having issues. Please make sure it is installed correctly. !!!
> If the problem persists, please try uninstalling the driver and installing the latest virtual controller driver
> ```

@joaomPT Nice we have some progress. 👍 

Did you try re-installing the virtual controller driver like the error suggested? Please make sure to follow the [PC installation section of the getting started guide.](https://github.com/Moehammered/switch-remote-play/wiki/01.-Getting-Started#pc-installation)

1. Please make sure you've followed the wiki for installation and setup.
2. If you've already installed the virtual controller, please try uninstalling and reinstalling it.
3. If it still doesn't work, please try installing the latest version of the controller driver and see if it helps

Since you're using Windows 11 I won't be able to debug or troubleshoot personally. There could be an issue that is related to Windows 11 but I can't say for sure. For now, please try what I've mentioned and let me know if anything changes.

Thanks.

**Comment by joaomPT** [comment]
Hey, It was the virtual driver that was missing. Thanks alot for the help :)
