### ISSUE TITLE
switch-remote-play Error Code 193

### ISSUE THREAD

**Issue by SenfCommander** [Moehammered/switch-remote-play#61]
Hi Moehammered, 
First of all, thx for your work on the switch app : )
I'm not able to connect my switch with my desktop tho, I get the exactly the same issue with the screen flickering and same error message as the person in this discussion here: https://github.com/Moehammered/switch-remote-play/issues/26
You suggested double clicking the .exe to run it should fix it, sadly it didn't change anything for me : ( 

How do I fix this?
![image](https://user-images.githubusercontent.com/110341967/182030695-bad2f4af-abb1-4fc4-8448-192cc07b4623.png)

**Comment by Moehammered** [comment]
Hi @SenfCommander, sorry for the delay mate. 
That error code means there is an issue running ffmpeg on your machine for some reason. 

Can you please try moving the remote play folder to a path with no spaces? So something like `c:\remote-play`

Next, can you try running switch remote play host as admin? 

Let me know how that goes.

**Comment by SenfCommander** [comment]
@Moehammered , you are a fcking genius! Made the folder you suggested, works like a charm now : )
Thanks so much, you did an amazing job with this homebrew (even the input lag is surprisingly low for a streamed connection
Thanks again!

**Comment by SenfCommander** [comment]
Sorry, one more issue, when I put a game into fullscreen, it only displays it on my pc monitor, the switch screen freezes ... @Moehammered

**Comment by Moehammered** [comment]
@SenfCommander haha I'm glad it worked. :)

As for the fullscreen thing, I've explained it in other issues, but basically it is a limitation of ffmpeg and how video capture works for desktop.

If you play a game or use an application that uses "dedicated fullscreen" then it asks Windows for exclusivity to render and causes issues with desktop capture.

If there's a "borderless fullscreen" mode for the game you're trying to play, make sure to set it to that. Otherwise, I'd recommend setting the game to Windowed mode and then using a program called Borderless Gaming to allow for borderless fullscreen.

**Comment by SenfCommander** [comment]
OK, good to hear thx : )
